import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    default: 'Github Resume Generator',
    template: '%s | Github Resume Generator',
  },
  description: 'Generated by create next app',
};

const RootLayout: FC = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>{children}</body>
  </html>
);

export default RootLayout;
